# Generated by Django 5.1.1 on 2025-02-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_text', models.TextField()),
                ('key_text_start_idx', models.IntegerField()),
                ('key_text_end_idx', models.IntegerField()),
                ('description', models.IntegerField()),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_manage_app.problem')),
            ],
        ),
    ]
