# Generated by Django 5.1.1 on 2025-03-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='description',
            field=models.TextField(),
        ),
    ]
