# Generated by Django 5.1.1 on 2025-02-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('problem_description', models.TextField()),
                ('input_description', models.TextField()),
                ('output_description', models.TextField()),
                ('time_limit', models.FloatField()),
                ('memory_limit', models.IntegerField()),
                ('level', models.CharField(default='easy', max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id', 'user_id'), name='unique_problem_id_user_id')],
            },
        ),
        migrations.CreateModel(
            name='ProblemAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_manage_app.algorithm')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_manage_app.problem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('problem_id', 'algorithm_id'), name='unique_problem_id_algorithm_id')],
            },
        ),
    ]
