# Generated by Django 5.1.1 on 2025-02-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.TextField(),
        ),
    ]
